language: java

branches:
  only:
    - master
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

before_install:
  - mkdir libs
  - wget "$NOTES_JAR_URL" -O ./libs/Notes.jar &> /dev/null
  - chmod +x gradlew

after_success:
  - bash <(curl -s https://codecov.io/bash)
